version: "3.8"
services:
  backend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: fastapi_backend
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../backend:/app/backend
      - ../frontend:/app/frontend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
      RABBITMQ_HOST: rabbitmq
      REDIS_HOST: redis
      PYTHONPATH: /app
    depends_on:
      - mariadb
      - rabbitmq
      - redis

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: mydatabase
      MARIADB_USER: myuser
      MARIADB_PASSWORD: mypassword
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "15672:15672"  # RabbitMQ Management UI
      - "5672:5672"    # RabbitMQ default port

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: celery_worker
    command: celery -A backend.celery_main worker --loglevel=info
    depends_on:
      - rabbitmq
      - redis
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
      RABBITMQ_HOST: rabbitmq
      REDIS_HOST: redis
      PYTHONPATH: /app
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  celery_beat:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: celery_beat
    command: celery -A backend.celery_main beat --loglevel=info
    depends_on:
      - rabbitmq
      - redis
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
      RABBITMQ_HOST: rabbitmq
      REDIS_HOST: redis
      PYTHONPATH: /app
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: redis://redis:6379/0
volumes:
  mariadb_data:
