services:
  backend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: fastapi_backend
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../backend:/app/backend
      - ../frontend:/app/frontend 
      - ../.env:/app/.env
    ports:
      - "8000:8000"
